import React,{useState,useEffect,useRef,useCallback} from 'react';
import {Search,MapPin,Compass,Layers3,Satellite,Database,Ellipsis,Upload,RefreshCw,Download,FileJson,HelpCircle,Sun,Moon,Check,ChevronLeft,ChevronRight,Play,Pause,CalendarDays,Plus,Minus,Home,ScanLine,Orbit,Unplug,ArrowRight,Grid2X2,Info,LoaderCircle,X} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tooltip,TooltipContent,TooltipProvider,TooltipTrigger} from '@/components/ui/tooltip';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuSeparator,DropdownMenuLabel} from '@/components/ui/dropdown-menu';
import {CommandDialog,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem,CommandShortcut} from '@/components/ui/command';
import {Toaster} from '@/components/ui/sonner';
import {useOverpass} from './use-overpass.js';
import {camera,stopOrbit,moveMap} from './map.js';
import {MapScene,Calendar,PassBoard,DistrictList,Evidence,Help} from './panels.jsx';

function Tool({label,icon:Icon,active,onClick,...props}){return <Tooltip><TooltipTrigger asChild><Button variant="ghost" size="icon" className={active?'tool-active':''} aria-label={label} aria-pressed={active===undefined?undefined:active} onClick={onClick} {...props}><Icon size={18} strokeWidth={1.7}/></Button></TooltipTrigger><TooltipContent side="right" sideOffset={12}>{label}</TooltipContent></Tooltip>;}
function TimeControls({h}){return <div className="time-settings"><div className="time-settings-heading"><h2>Explore through time</h2><p>Choose a year and an eight-day period.</p></div><div className="time-settings-selects"><label><span>Year</span><Select value={String(h.state.year)} onValueChange={year=>h.update({year:Number(year),playing:false})}><SelectTrigger aria-label="Year"><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:h.maxYear-2002},(_,i)=><SelectItem key={i} value={String(i+2003)}>{i+2003}</SelectItem>)}</SelectContent></Select></label><label><span>Playback speed</span><Select value={String(h.state.speed)} onValueChange={speed=>h.update({speed:Number(speed)})}><SelectTrigger aria-label="Playback speed"><SelectValue/></SelectTrigger><SelectContent>{[1,2,4].map(v=><SelectItem key={v} value={String(v)}>{v}×</SelectItem>)}</SelectContent></Select></label></div><div className="time-year-track"><Slider aria-label="Selected year" min={2003} max={h.maxYear} value={[h.state.year]} onValueChange={([year])=>h.update({year,playing:false})}/><div><span>2003</span><span>{h.maxYear}</span></div></div><p className="time-data-note">Only loaded records are shown. Import historical observations to explore earlier years.</p></div>;}
function LayersPanel({h,onHelp}){return <div className="layers-body"><section className="panel-section"><h3>Map layer</h3><div className="layer-options">{[['raw','Raw activity','Detections observed by MODIS and VIIRS.'],['adjusted','Adjusted activity','Compare calibrated activity against normal.'],['coverage','Clear-view coverage','Review measured observation coverage.']].map(([key,title,description])=>{const unavailable=key!=='raw'&&!h.hasEstimates;return <button key={key} className={`layer-option ${h.state.lens===key?'selected':''}`} aria-pressed={h.state.lens===key} disabled={unavailable} onClick={()=>h.update({lens:key})}><span className="layer-radio" aria-hidden="true">{h.state.lens===key&&<span/>}</span><span><strong>{title}</strong><small>{unavailable?'Import calibrated results to enable.':description}</small></span></button>;})}</div></section><section className="panel-section"><h3>Presentation</h3><Tabs value={h.state.view} onValueChange={view=>{stopOrbit();h.update({view});}}><TabsList className="presentation-tabs"><TabsTrigger value="sky"><Layers3 size={15}/>Map</TabsTrigger><TabsTrigger value="grid"><Grid2X2 size={15}/>Calendar</TabsTrigger></TabsList></Tabs></section><section className="panel-section"><h3>Map key</h3>{h.state.lens==='adjusted'?<div className="map-key"><span><i style={{background:'#e8f889'}}/>Unusually high</span><span><i style={{background:'#dfb976'}}/>Possibly unusual</span><span><i style={{background:'#51cabb'}}/>Usual range</span><p>Solid columns show lower bounds. Transparent caps show uncertainty.</p></div>:h.state.lens==='coverage'?<div className="map-key"><p>Coverage comes from imported fire-mask measurements. Below 30% clear view, burning is not judged.</p></div>:<div className="map-key"><span><i className="viirs-key"/>VIIRS · 375 m</span><span><i className="modis-key"/>MODIS · 1 km</span><p>Columns show detections on a logarithmic scale, rather than unique fires.</p></div>}</section><button className="context-link" onClick={onHelp}><Info size={16}/>About the map and its data<ArrowRight size={15}/></button></div>;}
function FleetControls({h}){return <section className="fleet-section"><h3>Fleet experiment</h3><p>Explore the record without Terra, Aqua, and S-NPP.</p><Button variant="outline" className="fleet-toggle" onClick={()=>{stopOrbit();h.update({grounded:!h.state.grounded});}}>{h.state.grounded?<RefreshCw size={15}/>:<Unplug size={15}/>} {h.state.grounded?'Re-launch fleet':'Ground the fleet'}</Button>{h.state.grounded&&<div className="fleet-results" role="status"><div><span>Raw detections retained</span><strong>{h.fleet.rawRetention===null?'—':h.fleet.rawRetention+'%'} <small>({h.fleet.kept}/{h.fleet.total})</small></strong></div><div><span>Adjusted verdicts retained</span><strong>{h.fleet.adjustedRetention===null?'Model needed':h.fleet.adjustedRetention+'%'}</strong></div></div>}</section>;}
const panelMeta={explore:['Explore districts','Find a place in the observation record.'],layers:['Layers','Choose what the map shows.'],satellites:['Satellites','See what each satellite observed.']};

export default function EarthWorkspace(){
  const notify=useCallback(message=>toast(message),[]),h=useOverpass(notify),[panel,setPanel]=useState(null),[evidence,setEvidence]=useState(false),[command,setCommand]=useState(false),[help,setHelp]=useState(false),[timeOpen,setTimeOpen]=useState(false),[theme,setTheme]=useState(()=>{try{return localStorage.getItem('afterglow-theme')||'dark';}catch{return'dark';}}),fileRef=useRef();
  useEffect(()=>{document.documentElement.classList.toggle('dark',theme==='dark');document.documentElement.dataset.theme=theme;try{localStorage.setItem('afterglow-theme',theme);}catch{}},[theme]);
  const openEvidence=()=>{setPanel(null);setEvidence(true);},togglePanel=name=>{setEvidence(false);setPanel(current=>current===name?null:name);},setCamera=mode=>{h.update({camera:mode});camera(mode,h.boundaries,h.state.area);};
  useEffect(()=>{const keydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCommand(v=>!v);return;}if(e.target.closest('input,select,textarea,button,[role="dialog"],[role="combobox"],[role="slider"]')||command||help||evidence||timeOpen)return;const key=e.key.toLowerCase();if(key==='g')h.update({view:h.state.view==='sky'?'grid':'sky'});else if(key==='t'){h.update({camera:'top'});camera('top',h.boundaries,h.state.area);}else if(key==='f'){stopOrbit();h.update({grounded:!h.state.grounded});setPanel('satellites');}else if(key==='?')setHelp(true);else if(key===' '&&e.target===document.body){e.preventDefault();h.play();}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','[',']','+','=','-'].includes(e.key)&&e.target===document.body){e.preventDefault();moveMap(e.key);}};window.addEventListener('keydown',keydown);return()=>window.removeEventListener('keydown',keydown);},[h,command,help,evidence,timeOpen]);
  const status=h.loading?'Connecting':h.error?'Connection unavailable':h.dataset.imported?'Imported data':h.dataset.stale?'Saved NASA record':'NASA FIRMS';
  const actions=[['Map view',Layers3,()=>h.update({view:'sky'})],['Grid calendar',Grid2X2,()=>h.update({view:'grid'})],['Explore districts',Compass,()=>setPanel('explore')],['Layers',Layers3,()=>setPanel('layers')],['Satellites',Satellite,()=>setPanel('satellites')],['Import data',Upload,()=>fileRef.current.click()],['Ground / re-launch fleet',Unplug,()=>{h.update({grounded:!h.state.grounded});setPanel('satellites');}],['Inspect evidence',Database,openEvidence],['Refresh NASA FIRMS',RefreshCw,h.refresh]];
  return <TooltipProvider delayDuration={250}><div className="earth-shell"><a className="skip-link" href="#workspace">Skip to map</a><main id="workspace" className={`earth-map ${h.state.view==='grid'?'calendar-view':''}`} tabIndex={-1} aria-label="Fire observation explorer"><MapScene h={h} onEvidence={openEvidence} notify={notify}/>{h.state.view==='grid'&&<div className="calendar-workspace"><Calendar h={h} onEvidence={openEvidence}/><Button variant="outline" size="sm" className="back-to-map" onClick={()=>h.update({view:'sky'})}><Layers3 size={15}/>Back to map</Button></div>}</main>
  <header className="earth-topbar"><a className="earth-brand" href="./" aria-label="Afterglow home"><svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M16 3 29 26H3L16 3Z" stroke="currentColor" strokeWidth="2"/><path d="M16 13 23 26H9l7-13Z" fill="currentColor"/></svg><strong>afterglow<span>.</span></strong></a><Button variant="ghost" className="earth-search" onClick={()=>setCommand(true)}><Search size={17}/><span>Search a district or action</span><kbd>Ctrl K</kbd></Button></header>
  <div className="earth-account-tools"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className={`data-status ${h.error?'has-error':''}`} aria-label="Data and settings">{h.loading?<LoaderCircle size={13} className="animate-spin"/>:<span className="status-dot"/>}<span>{status}</span><Ellipsis size={18}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="settings-menu"><DropdownMenuLabel>Data and settings</DropdownMenuLabel><DropdownMenuItem onSelect={()=>fileRef.current.click()}><Upload/>Import data</DropdownMenuItem><DropdownMenuItem disabled={h.loading} onSelect={h.refresh}><RefreshCw/>Refresh NASA FIRMS</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem onSelect={h.exportCSV}><Download/>Export observations CSV</DropdownMenuItem><DropdownMenuItem onSelect={h.exportEvidence}><FileJson/>Export evidence JSON</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun/>:<Moon/>}{theme==='dark'?'Light interface':'Dark interface'}</DropdownMenuItem><DropdownMenuItem onSelect={()=>setHelp(true)}><HelpCircle/>Help and flight tour</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
  <nav className="earth-tool-dock" aria-label="Explore map"><Tool label="Explore districts" icon={Compass} active={panel==='explore'} onClick={()=>togglePanel('explore')}/><Tool label="Layers" icon={Layers3} active={panel==='layers'} onClick={()=>togglePanel('layers')}/><Tool label="Satellites" icon={Satellite} active={panel==='satellites'} onClick={()=>togglePanel('satellites')}/><span className="dock-divider"/><Tool label="Inspect evidence" icon={Database} active={evidence} onClick={()=>evidence?setEvidence(false):openEvidence()}/></nav>
  {h.state.satellite&&<Button variant="secondary" size="sm" className="active-satellite" onClick={()=>h.update({satellite:null})}><Satellite size={14}/>{h.state.satellite}<X size={13}/><span className="sr-only">Show all satellites</span></Button>}{h.state.grounded&&<Button variant="secondary" size="sm" className="simulation-indicator" onClick={()=>togglePanel('satellites')}><Unplug size={13}/>Fleet simulation</Button>}{h.error&&<div className="map-error" role="status"><Info size={16}/><span>{h.error}</span><Button size="sm" variant="outline" onClick={h.refresh}>Retry</Button></div>}
  {h.state.view==='sky'&&<nav className="earth-camera" aria-label="Map camera"><Tool label="Zoom in" icon={Plus} onClick={()=>moveMap('+')}/><Tool label="Zoom out" icon={Minus} onClick={()=>moveMap('-')}/><span className="dock-divider"/><Tool label="Overview" icon={Home} onClick={()=>setCamera('overview')}/><Tool label={h.state.camera==='top'?'Tilt map':'Top-down'} icon={ScanLine} onClick={()=>setCamera(h.state.camera==='top'?'overview':'top')}/><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost" aria-label="More camera options"><Ellipsis size={18}/></Button></DropdownMenuTrigger><DropdownMenuContent side="left" align="end"><DropdownMenuItem onSelect={()=>setCamera('fit')}><Compass/>Fit selected area</DropdownMenuItem><DropdownMenuItem onSelect={()=>setCamera(h.state.camera==='orbit'?'overview':'orbit')}><Orbit/>{h.state.camera==='orbit'?'Stop orbit':'Orbit map'}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></nav>}
  <section className="earth-timeline" aria-label="Observation timeline"><Tool label={h.state.playing?'Pause':'Play season'} icon={h.state.playing?Pause:Play} onClick={h.play}/><Popover open={timeOpen} onOpenChange={open=>{setTimeOpen(open);if(open)setPanel(null);}}><PopoverTrigger asChild><Button variant="ghost" className="timeline-date" aria-label="Choose year and playback speed"><CalendarDays size={16}/><span>{h.date.short}<small>{h.state.year}</small></span></Button></PopoverTrigger><PopoverContent side="top" className="timeline-popover" align="center"><TimeControls h={h}/></PopoverContent></Popover><div className="timeline-track"><Tool label="Previous 8-day period" icon={ChevronLeft} onClick={()=>h.step(-1)}/><Slider aria-label="8-day period" min={0} max={45} value={[h.state.period]} onValueChange={([period])=>h.update({period,playing:false})}/><Tool label="Next 8-day period" icon={ChevronRight} onClick={()=>h.step(1)}/></div></section>
  <Sheet modal={false} open={!!panel} onOpenChange={open=>{if(!open)setPanel(null);}}><SheetContent side="left" className={`map-panel ${panel==='explore'?'explore-panel':''}`} onInteractOutside={event=>event.preventDefault()}><SheetHeader className="map-panel-header"><SheetTitle>{panelMeta[panel]?.[0]}</SheetTitle><SheetDescription>{panelMeta[panel]?.[1]}</SheetDescription></SheetHeader><div className="map-panel-content">{panel==='explore'&&<><Button variant="outline" className="panel-search" onClick={()=>setCommand(true)}><Search size={16}/>Find a district</Button><DistrictList h={h} onEvidence={openEvidence}/></>}{panel==='layers'&&<LayersPanel h={h} onHelp={()=>setHelp(true)}/>} {panel==='satellites'&&<><PassBoard h={h}/><FleetControls h={h}/></>}</div></SheetContent></Sheet>
  <Evidence h={h} open={evidence} onOpenChange={setEvidence}/><Help open={help} onOpenChange={setHelp}/><CommandDialog open={command} onOpenChange={setCommand}><CommandInput placeholder="Find a district or action…"/><CommandList><CommandEmpty>No matching district or action.</CommandEmpty><CommandGroup heading="Actions">{actions.map(([name,Icon,action])=><CommandItem key={name} onSelect={()=>{setCommand(false);action();}}><Icon/><span>{name}</span></CommandItem>)}</CommandGroup><CommandGroup heading="Districts">{h.areaNames.map(name=><CommandItem key={name} onSelect={()=>{setCommand(false);h.selectArea(name);}}><MapPin/><span>{name}</span>{name===h.state.area&&<CommandShortcut><Check size={14}/></CommandShortcut>}</CommandItem>)}</CommandGroup></CommandList></CommandDialog><input ref={fileRef} type="file" accept=".csv,.json,.geojson" hidden onChange={e=>{if(e.target.files[0])h.importFile(e.target.files[0]);e.target.value='';}}/><div className="sr-only" aria-live="polite">{h.loading?'Loading observations':h.headline} {h.state.grounded?'Fleet simulation active.':''}</div><Toaster theme={theme} position="top-center"/></div></TooltipProvider>;
}
