import React from 'react';
import {createRoot} from 'react-dom/client';
import EarthWorkspace from './earth-workspace.jsx';
import './ui.css';
import './map.css';
import 'maplibre-gl/dist/maplibre-gl.css';
import './panel-styles.css';
import './earth-layout.css';
const root=import.meta.hot?.data.root??createRoot(document.getElementById('app'));
if(import.meta.hot)import.meta.hot.data.root=root;
root.render(<EarthWorkspace/>);
